name = "SampledDomains"
uuid = "a82262f3-35bb-4fed-9e1b-5653a3e90076"
authors = ["Oleg Soloviev"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
